name: gamescout
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - sqlmodel
      - selenium
      - webdriver-manager
      - pytest
      - black
      - isort
      - flake8
      - loguru
      - numpy
      - numba
      - streamlit
      - plotly
      - pandas